### ISSUE TITLE
Any way to try this with 5.3?

### ISSUE THREAD

**Issue by chawker21** [develpr/alexa-app#19]
I would like to try this out to make an alexa app.  when I try to install it it says framework needs to be 5.3.* Is this something I can just change a setting on to try it or will it not work at all?  It seems a lot of the files are integrated into my project but I cant get the Develpr\App or the Bootstrap middleware to work.

**Comment by develpr** [comment]
Hey Chawker21, sorry it's taken me so long to get back to you here. #20 has a bit more details, but for now you should be able to simply bump the required Laravel version in the AlexaApp composer file to 5.3* and be able to test things out. Again, there appear to be some issues with 5.3 but if you check out #20 they seem relatively easily solved by using full class paths. I'm hoping to update the Laravel requirement myself fairly soon, or better yet merging a pull request :)

**Comment by develpr** [comment]
I went ahead and bumped the composer requirement to 5.4.x. If (and when!) you find issues with 5.3.* or 5.4.* please let me know!
