### ISSUE TITLE
Facades cause Ide-Helper to throw 'Segmentation Fault'

### ISSUE THREAD

**Issue by michaeljhopkins** [develpr/alexa-app#2]
Running `ide-helper:generate` causes a segmentation fault to be thrown when the faces are enabled from this app? Any idea what might be causing this? I wish I had more to give but there isn't much given to me.

http://i.imgur.com/DRaptgQ.png

EDIT: it looks like it's specifically the `AlexaRoute` facade that causes issue
EDIT: the issue also occurs with neither facade (only the service provider) when running `ide-helper:meta`

**Comment by develpr** [comment]
Thanks for this! I'll take a look at it soon. To be honest I haven't been keeping up with some of the recent changes to the ASK API so I'm going to spend some time soon going through everything again and making sure I'm at least a bit closer in terms of feature parity. And also fixing this :).

**Comment by robson83** [comment]
Give more context:

Tested it out on laravel 5.2, getting composer to grab source from dev-master. Something affects php-fpm, which runs a segmentation fault and the entire service is rebooted, returning a 502 error.

Downgraded to laravel 5.1, and ran composer without specifying the version from the master - just a regular composer require develpr/alexa-app and everything works.

Will try to debug it, but seems like the problem starts after running vendor:publish task. 

RD

**Comment by austinheap** [comment]
Any update on this? I'm also getting segmentation faults after following the installation guide with Laravel 5.2 and alexa-app@dev-master.

**Comment by develpr** [comment]
hey @austinheap, @robson83 , and @michaeljhopkins - sorry I've been so bad at fixing this issue!

I spent about two hours today trying to get back up to speed with all of this. I know I wrote it all, but still it's a bit tough when you don't look at / use it in a while to let things sink back in! 

All of this said, I have not spent much time with Laravel 5.2 yet or the changes that were made. I am able to confirm that in fact there is an error happening, but at this point it seems to be triggered simply by setting the service provider ` \Develpr\AlexaApp\Provider\LaravelServiceProvider::class,`? Can anybody confirm that? In other words, if you do nothing but install the latest version of AlexaApp and then add the service provider in `config/app.php` do you see an error?

Thanks all, and sorry again I've been so slow with this!

**Comment by develpr** [comment]
OK, I'm fairly certain at this point that the issue (at least the issue I'm seeing) is related to the aliases that I'm creating. I think something is happening where Aliases are being registered in the service provider, but for some reason with 5.2 when the classes themselves are being loaded they aren't "matching" with the Aliases. Which is causing some sort of circular recursive loop. Simply commenting out `$this->setupClassAliases();` in the `AlexaServiceProvider` may fix the issue, but then these aliases aren't available. I'll keep looking!

**Comment by develpr** [comment]
OK, I believe this is fixed. I've tagged 0.2.9 and this should resolve all issues with 5.2. 

If not, _please_ let me know and I'll take another look!
