### ISSUE TITLE
Not working with Laravel 5.3/5.4

### ISSUE THREAD

**Issue by S43534** [develpr/alexa-app#23]
This does not work with a fresh install on Laravel 5.3/5.4 due to requiring illuminate/routing v5.2.* in composer.json. May you please update the dependency or will this cause any issues?

Thanks & best regards
Sebastian

**Comment by develpr** [comment]
I've updated the composer requirements to 5.4.* so this should resolve this issue. If you wouldn't mind, please report any 5.4.* issues as you find them (one huge thing missing from this project is automated tests that make it easy for me to check things!)
