### ISSUE TITLE
Publish new version of alexa-app

### ISSUE THREAD

**Issue by vrajroham** [develpr/alexa-app#43]
It seems that recent version was published long time ago. Much improvements are contributed in library after that. There are much new features which are awesome but we can't use it. Hope you will publish it ASAP.

**Comment by vrajroham** [comment]
Awesome @develpr, Thanks for the quick response!

**Comment by develpr** [comment]
You are completely right! I went ahead and reviewed / merged in two outstanding pull requests and created a release.

I had hoped to spend some more time testing and putting together some tests before this release, but it's time to get something out there! 

Thanks for the reminder / prodding!

**Comment by vrajroham** [comment]
Looking forward to contribute more. Waiting to get updated on **Packagist**.

**Comment by vrajroham** [comment]
Latest version is yet not available on packagist to pull via composer. Even tried `dev-master` which is also far behind. https://packagist.org/packages/develpr/alexa-app
![screen shot 2017-11-11 at 11 32 02 am](https://user-images.githubusercontent.com/12662173/32686839-fffd829c-c6d3-11e7-90ed-43c9ca036a9b.png)

**Comment by vrajroham** [comment]
@develpr Yet latest tag is not available to pull via composer. Any idea why so? desperately needing updated version.

**Comment by develpr** [comment]
I just checked, in theory packagist is supposed to automatically pull in new tags / releases with some sort of webhook system from github but it doens't look like that happened.

I went ahead and manually updated the package in packagist and from what I can tell it's now updated.

@vrajroham I'll re-open this issue until you confirm it was updated for you as well! Sorry about that!

**Comment by vrajroham** [comment]
@develpr Thanks for your quick fix.I confirm that latest tag is now available on packagist. I have some suggestions/fixes and doc improvements in pipline for this package. Soon I'll get back with it. Really thanks for great package!
