### ISSUE TITLE
Amazon responds with a 404

### ISSUE THREAD

**Issue by frantischek** [develpr/alexa-app#46]
Hi,
I'm getting a 404 in the Amazon Service Simulator. I don't know if it is a bug or not, but I have seen in some discussions that many developers have problems with this package.
My Utterance is just "Open ......" (the launchIntent). My middleware logs all requests and responses. 
The request type is "LaunchRequest"
Response:
```
    \"exception\": \"Symfony\\\\Component\\\\HttpKernel\\\\Exception\\\\NotFoundHttpException\",
    \"file\": \"/var/www/alexa/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php\",
    \"line\": 179,
```
I defined my endpoint at amazon developers page as https://alexa.mydomain.de/alexa

My routes\web.php looks like this:
```
AlexaRoute::launch('/alexa', function () {
    return Alexa::say("Oh yes")->endSession();
});
```
Can someone help me please?
Thanks

Edit: Laravel Framework 5.5.28

**Comment by vrajroham** [comment]
@frantischek This error occurred so many times for me. Did you tried registering provider in `config/app`? Though there is auto discovery is available with package but it wont help me.

Adding provider and alias in `config/app.php` helped me. 

Let me know if there is any I can help more.

**Comment by frantischek** [comment]
Yes, I have these entries in my config\app.php
```
    'providers' => [
[...]
        \Develpr\AlexaApp\Provider\LaravelServiceProvider::class,
[...]
    'aliases' => [
[...]
        'AlexaRoute' => \Develpr\AlexaApp\Facades\AlexaRouter::class,
        'Alexa' => \Develpr\AlexaApp\Facades\Alexa::class,
```

**Comment by vrajroham** [comment]
@frantischek Seems everything correct.

Try setting controller like below,

    AlexaRoute::launch('/alexa', '\App\Http\Controllers\AlexaController@launch');

It seems silly, but let's see if this helps.

**Comment by frantischek** [comment]
Thats strange. I recieve this error in my log:
```
    \"message\": \"Class 'App\\\\Http\\\\Controllers\\\\Alexa' not found\",
    \"exception\": \"Symfony\\\\Component\\\\Debug\\\\Exception\\\\FatalThrowableError\",
    \"file\": \"/var/www/alexa/app/Http/Controllers/AlexaController.php\",
My Controller looks like this:
```
namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AlexaController extends Controller
{
    public function launch() {
        return Alexa::say("Oh yes")->endSession();
    }
}
```
And my web.php
```
AlexaRoute::launch('/alexa', '\App\Http\Controllers\AlexaController@launch');

**Comment by wertmenschen** [comment]
Looks like you just forgot to "use Alexa" in AlexaController.

**Comment by vrajroham** [comment]
@frantischek Really weird. I have gone through this frustration. 

Try running `composer dump-autoload`

**Comment by vrajroham** [comment]
@frantischek Meanwhile I've uploaded my working sample project https://github.com/vrajroham/sample-laravel-alexa-integration here. Hope you can get any clue.

**Comment by wertmenschen** [comment]
Any clue: 
@vrajroham has "use Develpr\AlexaApp\Facades\Alexa;".
@frantischek hasn't.

**Comment by vrajroham** [comment]
@wertmenschen Yes you are right. 👍

**Comment by frantischek** [comment]
@wertmenschen 
Looks like you just forgot to "use Alexa" in AlexaController.

That did the trick. Strange. 
Thank you very much.
