### ISSUE TITLE
Code style and repo best-practices

### ISSUE THREAD

**Issue by colinodell** [develpr/alexa-app#9]
Would you be opposed to me cleaning up the code style to be PSR-2 compliant (so that it passes StyleCI checks)?

I'd also like to perform some minor housekeeping like:
- Using consistent indentation in `composer.json` (spaces instead of tabs)
- Adding a branch alias for `dev-master` (like I do here for [league/commonmark](https://github.com/thephpleague/commonmark/blob/master/composer.json#L62))
- Adding a `LICENSE` file to the repo root
- Adding a `CHANGELOG` and populating it for you

Stuff like that.

I just don't want to start on this work if you're not interested :)

**Comment by develpr** [comment]
I would love it, and be super super appreciative!

**Comment by colinodell** [comment]
Awesome!  I'll start on that sometime this week (or perhaps even tonight on the off chance my two latest PRs get merged :wink:)
